### ISSUE TITLE
On Profiles & Folders page, user is not able clear the tags field

### ISSUE THREAD

**Issue by vishavsoftiatric** [chameleonmode/chameleon.app-community#95]
**Screen**: Profiles & Folders

**Description**:  When user clear the Tags field and click on the save button, the user navigate to other page and then navigate back to Profiles & Folders page, the value in Tags field are displaying again

**Steps to reproduce**:

1. Login to application
2. Click on Profiles & Folders icon
3.  Clear value from tags field 
4. Click on save button
5. Go to another page
6. Navigate back to Profiles & Folders icon

**Bug recording**: https://drive.google.com/file/d/1vJV_KqmM-1dLS-KSKhLb5Vhp1LoUP8_Y/view?usp=drive_link

**Comment by ezexe** [comment]
might need server side debugging lmk

**Comment by JackMutobu** [comment]
Fixed in [PR #26](https://github.com/chameleonmode/Chameleon-lib/pull/26)

**Comment by vishavsoftiatric** [comment]
@ezexe @JackMutobu I have tested this issue on latest build and found the following:
when clear the tags field and click on save button, the error popup message is getting displaying

**Bug Screenshot**: https://prnt.sc/PDnciXL1mdCA

**Comment by JackMutobu** [comment]
@vishavsoftiatric I made a new update, check it then let me know if you still have the same issue

**Comment by vishavsoftiatric** [comment]
@ezexe @JackMutobu I have tested this on latest build and found error message is still displaying.

**Bug Screenshot**: https://prnt.sc/_f3TvjmTVhZ7

**Comment by vishavsoftiatric** [comment]
@ezexe I have tested this issue on latest build and found this issue is still displaying.

**Comment by JackMutobu** [comment]
@JackMutobu Can you show a step-by-step way to reproduce the bug? I am on 2025.0.40 and the issue does not show up

**Comment by vishavsoftiatric** [comment]
@JackMutobu @ezexe I have tested this issue on version(2025.0.4.0) and followed the pervious steps according, yet this issue is still occurring

**Bug Recording**: https://drive.google.com/file/d/1VRCIapcs5gOM8vjxsSVvA4qBALELOr-z/view?usp=drive_link

**Comment by vishavsoftiatric** [comment]
@ezexe @JackMutobu I have tested this issue on latest build and found now error message displaying
**Bug Screenshot**: https://prnt.sc/8W3Rd5DgCnGr
